language: csharp
sudo: false
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  
  - wget https://downloads.arduino.cc/arduino-1.6.11-linux64.tar.xz
  - tar xf arduino-1.6.11-linux64.tar.xz
  - mv arduino-1.6.11 $HOME/arduino_ide
  - export PATH="$HOME/arduino_ide:$PATH"

install: 
  - arduino --pref "compiler.warning_level=all" --save-prefs

script:
  - arduino --verify --board arduino:avr:uno $PWD/FanControl/FanControl.ino
  - xbuild /p:Configuration=Release "C# Client/iRacingSLI.sln"